Corrections  and edits to FlaskManagerCore.cs
Shortend the class name FlaskManagerCorePlugin to FlaskManagerCore

Line 59, added PluginNmame PluginName = "Flask Manager";

This is needed to give the Plugin a more readable name, otherwise it
will use the first class name(FlaskManagerCore) as its name in plugins
menu

commited out line 256, as it was giving a compile error :

Severity Code Description Project File Line Suppression State
Error CS0117 'FlaskAction' does not contain a definition for
'BeforeFight' FlaskManager C:\Game
Tools\PoEHUD\src\bin\x64\Debug\plugins\AutoFlaskManager\src\AutoFlaskManager\FlaskManagerCore.cs
256 Active